export const Projects = [
    {
        name: 'Uselect Finance',
        id: 'uselect',
        image: 'https://lukegong.com/wp-content/uploads/2018/01/uselectfiance-new-1.png',
        type: ['website', 'all'],
        link: "http://uselectfinance.com/index.php",
        description: "<p>From Uselect Finance:</p><p><em>“Uselect Finance aims to provide the most suitable mortgage product to you since day one we established. We are honor to be the broker that our client trusted. We specialize in tailor-made residential and commercial mortgage loan with the aim to provide the best mortgage solution that collaborates with individual situation and demand.</em></p><p><em>We offer an extensive range of loan products from banks and other financial institutions, provide the newest loan information, promotions and policies, and present the lowest possible rates and best offers to our customers.</em></p><p><em>Our professional consultants will choose the best possible products for customers, based on their individual financial abilities, allowing customers to save time, effort and money.</em></p><p><em>We have professional loan application support officers to make sure the application documents are successfully submitted and pre-approved by banks.”</em></p>",
        contribution: "<p>This website is building using pure php language.&nbsp; I build this site from scratch</p><ul><li>FE: Bootstrap</li><li>BE: PHP</li><li>DB: Mysql</li><li>Multilingual: English/Chinese</li></ul>",
        percentage: 90,
    },
    {
        name: 'Room View',
        id: 'roomview',
        image: 'https://lukegong.com/wp-content/uploads/2018/01/room_view.gif',
        type: ['ionic', 'webgl', 'all'],
        link: "http://uselectfinance.com/index.php",
        description: "<p>From Uselect Finance:</p><p><em>“Uselect Finance aims to provide the most suitable mortgage product to you since day one we established. We are honor to be the broker that our client trusted. We specialize in tailor-made residential and commercial mortgage loan with the aim to provide the best mortgage solution that collaborates with individual situation and demand.</em></p><p><em>We offer an extensive range of loan products from banks and other financial institutions, provide the newest loan information, promotions and policies, and present the lowest possible rates and best offers to our customers.</em></p><p><em>Our professional consultants will choose the best possible products for customers, based on their individual financial abilities, allowing customers to save time, effort and money.</em></p><p><em>We have professional loan application support officers to make sure the application documents are successfully submitted and pre-approved by banks.”</em></p>",
        contribution: "<p>This website is building using pure php language.&nbsp; I build this site from scratch</p><ul><li>FE: Bootstrap</li><li>BE: PHP</li><li>DB: Mysql</li><li>Multilingual: English/Chinese</li></ul>",
        percentage: 90,        
    },
    {
        name: 'Movie Search',
        id: 'moviesearch',
        image: 'https://lukegong.com/wp-content/uploads/2018/01/FireShot-Capture-3-Home-http___localhost_8100_.png',
        type: ['ionic', 'all'],
        link: "http://uselectfinance.com/index.php",
        description: "<p>From Uselect Finance:</p><p><em>“Uselect Finance aims to provide the most suitable mortgage product to you since day one we established. We are honor to be the broker that our client trusted. We specialize in tailor-made residential and commercial mortgage loan with the aim to provide the best mortgage solution that collaborates with individual situation and demand.</em></p><p><em>We offer an extensive range of loan products from banks and other financial institutions, provide the newest loan information, promotions and policies, and present the lowest possible rates and best offers to our customers.</em></p><p><em>Our professional consultants will choose the best possible products for customers, based on their individual financial abilities, allowing customers to save time, effort and money.</em></p><p><em>We have professional loan application support officers to make sure the application documents are successfully submitted and pre-approved by banks.”</em></p>",
        contribution: "<p>This website is building using pure php language.&nbsp; I build this site from scratch</p><ul><li>FE: Bootstrap</li><li>BE: PHP</li><li>DB: Mysql</li><li>Multilingual: English/Chinese</li></ul>",
        percentage: 90,
    },
    {
        name: 'The Beauty Insider',
        id: 'beautyinsider',
        image: 'https://lukegong.com/wp-content/uploads/2017/12/The-Beauty-Insider.png',
        type: ['website', 'all'],
        link: "http://uselectfinance.com/index.php",
        description: "<p>From Uselect Finance:</p><p><em>“Uselect Finance aims to provide the most suitable mortgage product to you since day one we established. We are honor to be the broker that our client trusted. We specialize in tailor-made residential and commercial mortgage loan with the aim to provide the best mortgage solution that collaborates with individual situation and demand.</em></p><p><em>We offer an extensive range of loan products from banks and other financial institutions, provide the newest loan information, promotions and policies, and present the lowest possible rates and best offers to our customers.</em></p><p><em>Our professional consultants will choose the best possible products for customers, based on their individual financial abilities, allowing customers to save time, effort and money.</em></p><p><em>We have professional loan application support officers to make sure the application documents are successfully submitted and pre-approved by banks.”</em></p>",
        contribution: "<p>This website is building using pure php language.&nbsp; I build this site from scratch</p><ul><li>FE: Bootstrap</li><li>BE: PHP</li><li>DB: Mysql</li><li>Multilingual: English/Chinese</li></ul>",
        percentage: 90,
    },
    {
        name: 'CAOA',
        id: 'caoa',
        image: 'https://lukegong.com/wp-content/uploads/2017/12/CAOA.png',
        type: ['website', 'all'],
        link: "http://uselectfinance.com/index.php",
        description: "<p>From Uselect Finance:</p><p><em>“Uselect Finance aims to provide the most suitable mortgage product to you since day one we established. We are honor to be the broker that our client trusted. We specialize in tailor-made residential and commercial mortgage loan with the aim to provide the best mortgage solution that collaborates with individual situation and demand.</em></p><p><em>We offer an extensive range of loan products from banks and other financial institutions, provide the newest loan information, promotions and policies, and present the lowest possible rates and best offers to our customers.</em></p><p><em>Our professional consultants will choose the best possible products for customers, based on their individual financial abilities, allowing customers to save time, effort and money.</em></p><p><em>We have professional loan application support officers to make sure the application documents are successfully submitted and pre-approved by banks.”</em></p>",
        contribution: "<p>This website is building using pure php language.&nbsp; I build this site from scratch</p><ul><li>FE: Bootstrap</li><li>BE: PHP</li><li>DB: Mysql</li><li>Multilingual: English/Chinese</li></ul>",
        percentage: 90,
    },
    {
        name: 'Young Academics',
        id: 'youngacademics',
        image: 'https://lukegong.com/wp-content/uploads/2017/12/Young-Academics.png',
        type: ['website', 'all'],
        link: "http://uselectfinance.com/index.php",
        description: "<p>From Uselect Finance:</p><p><em>“Uselect Finance aims to provide the most suitable mortgage product to you since day one we established. We are honor to be the broker that our client trusted. We specialize in tailor-made residential and commercial mortgage loan with the aim to provide the best mortgage solution that collaborates with individual situation and demand.</em></p><p><em>We offer an extensive range of loan products from banks and other financial institutions, provide the newest loan information, promotions and policies, and present the lowest possible rates and best offers to our customers.</em></p><p><em>Our professional consultants will choose the best possible products for customers, based on their individual financial abilities, allowing customers to save time, effort and money.</em></p><p><em>We have professional loan application support officers to make sure the application documents are successfully submitted and pre-approved by banks.”</em></p>",
        contribution: "<p>This website is building using pure php language.&nbsp; I build this site from scratch</p><ul><li>FE: Bootstrap</li><li>BE: PHP</li><li>DB: Mysql</li><li>Multilingual: English/Chinese</li></ul>",
        percentage: 90,
    },
    {
        name: 'Ignazia',
        id: 'ignazia',
        image: 'https://lukegong.com/wp-content/uploads/2017/12/Ignazia.png',
        type: ['website', 'all'],
        link: "http://uselectfinance.com/index.php",
        description: "<p>From Uselect Finance:</p><p><em>“Uselect Finance aims to provide the most suitable mortgage product to you since day one we established. We are honor to be the broker that our client trusted. We specialize in tailor-made residential and commercial mortgage loan with the aim to provide the best mortgage solution that collaborates with individual situation and demand.</em></p><p><em>We offer an extensive range of loan products from banks and other financial institutions, provide the newest loan information, promotions and policies, and present the lowest possible rates and best offers to our customers.</em></p><p><em>Our professional consultants will choose the best possible products for customers, based on their individual financial abilities, allowing customers to save time, effort and money.</em></p><p><em>We have professional loan application support officers to make sure the application documents are successfully submitted and pre-approved by banks.”</em></p>",
        contribution: "<p>This website is building using pure php language.&nbsp; I build this site from scratch</p><ul><li>FE: Bootstrap</li><li>BE: PHP</li><li>DB: Mysql</li><li>Multilingual: English/Chinese</li></ul>",
        percentage: 90,
    },
    {
        name: 'Decor Systems',
        id: 'decor',
        image: 'https://lukegong.com/wp-content/uploads/2017/12/Decor-Systems-659x1024.png',
        type: ['website', 'all'],
        link: "http://uselectfinance.com/index.php",
        description: "<p>From Uselect Finance:</p><p><em>“Uselect Finance aims to provide the most suitable mortgage product to you since day one we established. We are honor to be the broker that our client trusted. We specialize in tailor-made residential and commercial mortgage loan with the aim to provide the best mortgage solution that collaborates with individual situation and demand.</em></p><p><em>We offer an extensive range of loan products from banks and other financial institutions, provide the newest loan information, promotions and policies, and present the lowest possible rates and best offers to our customers.</em></p><p><em>Our professional consultants will choose the best possible products for customers, based on their individual financial abilities, allowing customers to save time, effort and money.</em></p><p><em>We have professional loan application support officers to make sure the application documents are successfully submitted and pre-approved by banks.”</em></p>",
        contribution: "<p>This website is building using pure php language.&nbsp; I build this site from scratch</p><ul><li>FE: Bootstrap</li><li>BE: PHP</li><li>DB: Mysql</li><li>Multilingual: English/Chinese</li></ul>",
        percentage: 90,
    },
    {
        name: 'AV1',
        id: 'av1',
        image: 'https://lukegong.com/wp-content/uploads/2017/12/AV1-407x1024.png',
        type: ['website', 'all'],
        link: "http://uselectfinance.com/index.php",
        description: "<p>From Uselect Finance:</p><p><em>“Uselect Finance aims to provide the most suitable mortgage product to you since day one we established. We are honor to be the broker that our client trusted. We specialize in tailor-made residential and commercial mortgage loan with the aim to provide the best mortgage solution that collaborates with individual situation and demand.</em></p><p><em>We offer an extensive range of loan products from banks and other financial institutions, provide the newest loan information, promotions and policies, and present the lowest possible rates and best offers to our customers.</em></p><p><em>Our professional consultants will choose the best possible products for customers, based on their individual financial abilities, allowing customers to save time, effort and money.</em></p><p><em>We have professional loan application support officers to make sure the application documents are successfully submitted and pre-approved by banks.”</em></p>",
        contribution: "<p>This website is building using pure php language.&nbsp; I build this site from scratch</p><ul><li>FE: Bootstrap</li><li>BE: PHP</li><li>DB: Mysql</li><li>Multilingual: English/Chinese</li></ul>",
        percentage: 90,
    },
];

export const PorjectList = [
    {
        name: "All",
        type: "all",
        isChecked: true
    },
    {
        name: "Websites",
        type: "website",
        isChecked: false
    },
    {
        name: "Mobile",
        type: "ionic",
        isChecked: false
    },
    {
        name: "WebGL",
        type: "webgl",
        isChecked: false
    },
]